# Generated by Django 4.2 on 2023-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1234-03-23'),
            preserve_default=False,
        ),
    ]
